#version 450

layout(local_size_x = 256) in;

layout(std430, binding = 44) buffer ActiveBuffer { uint activeFlags[]; };
layout(std430, binding = 40) readonly buffer NextBuffer { int nextActiveTime[]; };

layout(push_constant) uniform PushConstants {
    int nParticles;
    int stepTicks;
    int globalTime;
    float minDt;
    float gravityG;
    float boxCenter;
    float boxSize;
    float gravitySoftening;
} pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= uint(pc.nParticles)) return;
    activeFlags[i] = pc.globalTime >= nextActiveTime[i] ? 1u : 0u;
}
