#version 450

layout(local_size_x = 256) in;

layout(std430, binding = 22) readonly buffer Cells { uvec2 cells[]; };
layout(std430, binding = 28) buffer CellStart { uint cellStart[]; };
layout(std430, binding = 29) buffer CellEnd { uint cellEnd[]; };

layout(push_constant) uniform PushConstants {
    int nParticles;
    int stepTicks;
    int globalTime;
    float minDt;
    float gravityG;
    float boxCenter;
    float boxSize;
    float gravitySoftening;
    int workItems;
    int parentStride;
    int stride;
    int sortIteration;
} pc;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= uint(pc.nParticles)) return;
    uint cell = cells[index].x;
    atomicMin(cellStart[cell], index);
    atomicMax(cellEnd[cell], index);
}
