#version 450

layout(local_size_x = 256) in;

layout(std430, binding = 14) buffer Tree { int tree[]; };
layout(std430, binding = 18) readonly buffer TreeLevel { int treeLevel[]; };
layout(std430, binding = 23) readonly buffer InverseCellData { uvec2 inverseCellData[]; };

layout(push_constant) uniform PushConstants {
    int nParticles;
    int stepTicks;
    int globalTime;
    float minDt;
    float gravityG;
    float boxCenter;
    float boxSize;
    float gravitySoftening;
    int workItems;
    int parentStride;
    int stride;
    int sortIteration;
    int cellTableSize;
    int uncheckedParentStride;
    int gravityLevelParity;
    int dispatchOffset;
} pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= uint(pc.workItems)) return;
    int treePointer = treeLevel[pc.parentStride + int(i)];
    if (treePointer < 0) return;
    int nParticlesInLeaf = tree[treePointer];
    if (nParticlesInLeaf == 0) return;

    int start = treePointer + 2;
    int end = start + nParticlesInLeaf;
    for (int p = start; p < end; ++p) {
        int oldParticle = tree[p];
        if (oldParticle >= 0 && oldParticle < pc.nParticles) {
            tree[p] = int(inverseCellData[oldParticle].y);
        }
    }
}
